DefaultContentLanguage = "en"
baseURL = "https://www.corwinkcosmetics.com/"
canonifyUrls = "false"
languageCode = "en-us"
publishdir = "public"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "FAQ"
url = "/faq"
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[[menu.main]]
name = "Shop"
url = "/products"
weight = 2
[outputs]
home = ["HTML", "RSS", "JSON"]
[taxonomies]
category = "categories"
collection = "collections"
eyeliner = "eyeliners"
lash-material = "lash-materials"
lash-type = "lash-types"
tag = "tags"
